package Modelos;
// Generated 9/10/2019 12:46:43 AM by Hibernate Tools 4.3.1



/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private String clave;
     private String nombre;
     private String domicilio;
     private String telefono;

    public Persona() {
    }

	
    public Persona(String clave) {
        this.clave = clave;
    }
    public Persona(String clave, String nombre, String domicilio, String telefono) {
       this.clave = clave;
       this.nombre = nombre;
       this.domicilio = domicilio;
       this.telefono = telefono;
    }
   
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


